// Autogenerated from Pigeon (v25.3.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.myflutterproject

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 原生数据
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeBean (
  val id: Long,
  val name: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeBean {
      val id = pigeonVar_list[0] as Long
      val name = pigeonVar_list[1] as String
      return NativeBean(id, name)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeBean) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Flutter数据
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FlutterBean (
  val fId: Long,
  val fName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FlutterBean {
      val fId = pigeonVar_list[0] as Long
      val fName = pigeonVar_list[1] as String
      return FlutterBean(fId, fName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fId,
      fName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FlutterBean) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeBean.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FlutterBean.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeBean -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is FlutterBean -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 重点关心这两个抽象类
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface FlutterToNative {
  fun loadNativeInfo(id: Long): NativeBean

  companion object {
    /** The codec used by FlutterToNative. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `FlutterToNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterToNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.myflutterproject.FlutterToNative.loadNativeInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.loadNativeInfo(idArg))
            } catch (exception: Throwable) {
              PigeonApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class NativeToFlutter(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NativeToFlutter. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
  }
  fun getFlutterInfo(idArg: Long, callback: (Result<FlutterBean>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.myflutterproject.NativeToFlutter.getFlutterInfo$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(idArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as FlutterBean
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(PigeonApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
